version: '3.4'

services:
  userregistration.api:
    image: ${DOCKER_REGISTRY-}userregistrationapi
    build:
      context: .
      dockerfile: UserRegistration.Api/Dockerfile
    ports:
      - "5003:443"
      - "5004:80"
    depends_on: 
      - db
  
  db:
    image: sawarni/blogpostdbsql
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    #  - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  blogpost.api:
    image: ${DOCKER_REGISTRY-}blogpostapi
    build:
      context: .
      dockerfile: BlogPost.Api/Dockerfile
    ports:
      - "5001:443"
      - "5002:80"
    depends_on: 
      - db
  
volumes:
  dbdata:
